apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nykb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0067-tenant/tkrw-pr712-0075-0067-app/devfile-sample-nykb@sha256:8605da4ea99d9727307868e00f75b13acfc5ac174048b21f4e901b94fac851d6
        name: my-nodejs
        resources: {}
status: {}
